### ISSUE TITLE
单机多卡训练过程中，会直接卡住，超时后报错

### ISSUE THREAD

**Issue by congyi-lcy** [taohan10200/STEERER#20]
作者您好，首先十分感谢贡献了这么棒的工作。最近在学习您的代码时，发现了训练过程中的一些问题，这十分困扰我。如果您能给予一些解决方案或建议，我将十分感激！

言简意赅，我在单机多卡（4个GPU，3090）训练模型时，会随机地卡在某一个epoch上（可能是第2个，可能是第10个，也可能是第20个），然后之后会说NCCL通信超时的报错。大概是卡在loss.backward()里面的 torch.distributed.all_reduce这里，具体报错如
log_error.txt：

```
Loss: 0.004, MAE:  120.83, Best_MAE:  120.8300 MSE:  357.8124,Best_MSE:  357.8124                                                              
[E ProcessGroupNCCL.cpp:587] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(OpType=ALLREDUCE, Timeout(ms)=3600000) ran for 360
6109 milliseconds before timing out.                                                                                                           
[E ProcessGroupNCCL.cpp:587] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(OpType=ALLREDUCE, Timeout(ms)=3600000) ran for 360
6191 milliseconds before timing out.                                                                                                           
[E ProcessGroupNCCL.cpp:587] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(OpType=ALLREDUCE, Timeout(ms)=3600000) ran for 360
6274 milliseconds before timing out.                                                                                                           
[E ProcessGroupNCCL.cpp:587] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(OpType=ALLREDUCE, Timeout(ms)=3600000) ran for 360
6654 milliseconds before timing out.                                                                                                           
Traceback (most recent call last):                                                                                                             
  File "/home/cliu/testcode/STEERER_torch1-10-1/tools/train_cc.py", line 382, in <module>                                                      
    main()                                                                                                                                     
  File "/home/cliu/testcode/STEERER_torch1-10-1/tools/train_cc.py", line 312, in main                                                          
    train(config, epoch, config.train.end_epoch,                                                                                               
  File "/home/cliu/testcode/STEERER_torch1-10-1/./lib/core/cc_function.py", line 92, in train                                                  
    loss.backward()                                                                                                                            
  File "/home/cliu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/_tensor.py", line 307, in backward                                    
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)                                                         
  File "/home/cliu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/autograd/__init__.py", line 154, in backward                          
    Variable._execution_engine.run_backward(                                                                                                   
  File "/home/cliu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/autograd/function.py", line 199, in apply                             
    return user_fn(self, *args)
  File "/home/cliu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/_functions.py", line 99, in backward
    torch.distributed.all_reduce(
  File "/home/cliu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1287, in all_reduce
    work = group.allreduce([tensor], opts)
RuntimeError: NCCL communicator was aborted on rank 1.  Original reason for failure was: [Rank 1] Watchdog caught collective operation timeout:
 WorkNCCL(OpType=ALLREDUCE, Timeout(ms)=3600000) ran for 3606109 milliseconds before timing out.
Traceback (most recent call last):
  File "/home/cliu/testcode/STEERER_torch1-10-1/tools/train_cc.py", line 382, in <module>
    main()
  File "/home/cliu/testcode/STEERER_torch1-10-1/tools/train_cc.py", line 312, in main
    train(config, epoch, config.train.end_epoch,
  File "/home/cliu/testcode/STEERER_torch1-10-1/./lib/core/cc_function.py", line 92, in train
    loss.backward()
  File "/home/cliu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/_tensor.py", line 307, in backward
  Variable._execution_engine.run_backward(                                                                                          [75/1812]
  File "/home/cliu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/autograd/function.py", line 199, in apply
    return user_fn(self, *args)
  File "/home/cliu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/_functions.py", line 99, in backward
    torch.distributed.all_reduce(
  File "/home/cliu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1287, in all_reduce
    work = group.allreduce([tensor], opts)
RuntimeError: NCCL communicator was aborted on rank 2.  Original reason for failure was: [Rank 2] Watchdog caught collective operation timeout:
 WorkNCCL(OpType=ALLREDUCE, Timeout(ms)=3600000) ran for 3606654 milliseconds before timing out.
Traceback (most recent call last):
  File "/home/cliu/testcode/STEERER_torch1-10-1/tools/train_cc.py", line 382, in <module>
Traceback (most recent call last):
  File "/home/cliu/testcode/STEERER_torch1-10-1/tools/train_cc.py", line 382, in <module>
    main()
  File "/home/cliu/testcode/STEERER_torch1-10-1/tools/train_cc.py", line 312, in main
    train(config, epoch, config.train.end_epoch,
  File "/home/cliu/testcode/STEERER_torch1-10-1/./lib/core/cc_function.py", line 92, in train
    loss.backward()
  File "/home/cliu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/cliu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/autograd/__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
  File "/home/cliu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/autograd/function.py", line 199, in apply
    return user_fn(self, *args)
  File "/home/cliu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/_functions.py", line 99, in backward
    torch.distributed.all_reduce(
  File "/home/cliu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1287, in all_reduce
    work = group.allreduce([tensor], opts)
RuntimeError: NCCL communicator was aborted on rank 0.  Original reason for failure was: [Rank 0] Watchdog caught collective operation timeout:
 WorkNCCL(OpType=ALLREDUCE, Timeout(ms)=3600000) ran for 3606274 milliseconds before timing out.
    main()
  File "/home/cliu/testcode/STEERER_torch1-10-1/tools/train_cc.py", line 312, in main
    train(config, epoch, config.train.end_epoch,
  File "/home/cliu/testcode/STEERER_torch1-10-1/./lib/core/cc_function.py", line 92, in train
    loss.backward()
  File "/home/cliu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/cliu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/autograd/__init__.py", line 154, in backward
  Variable._execution_engine.run_backward(                                                                                          [37/1812]
  File "/home/cliu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/autograd/function.py", line 199, in apply
    return user_fn(self, *args)
  File "/home/cliu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/_functions.py", line 99, in backward
    torch.distributed.all_reduce(
  File "/home/cliu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1287, in all_reduce
    work = group.allreduce([tensor], opts)
RuntimeError: NCCL communicator was aborted on rank 3.  Original reason for failure was: [Rank 3] Watchdog caught collective operation timeout:
 WorkNCCL(OpType=ALLREDUCE, Timeout(ms)=3600000) ran for 3606191 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:341] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU oper
ations might run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:341] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU oper
ations might run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
terminate called after throwing an instance of 'std::runtime_error  what():  [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(Op
Type=ALLREDUCE, Timeout(ms)=3600000) ran for 3606274 milliseconds before timing out.'

  what():  [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(OpType=ALLREDUCE, Timeout(ms)=3600000) ran for 3606191 milliseconds 
before timing out.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 3366366) of binary: /home/cliu/anaconda3/envs/py3
9/bin/python
Traceback (most recent call last):
  File "/home/cliu/anaconda3/envs/py39/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/cliu/anaconda3/envs/py39/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/cliu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/cliu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/cliu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/cliu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/cliu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/cliu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
    torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train_cc.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-07-25_13:12:26
  host      : g01
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 3366367)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-07-25_13:12:26
  host      : g01
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 3366368)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-07-25_13:12:26
  host      : g01
  rank      : 3 (local_rank: 3)
  exitcode  : -6 (pid: 3366369)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 3366369
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-07-25_13:12:26
  host      : g01
  rank      : 0 (local_rank: 0)
  exitcode  : -6 (pid: 3366366)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 3366366
============================================================
```

我目前大致做了如下尝试或排查，但是还是没有解决这个问题：
  1、数据集本身并不存在问题。即使存在一些负样本，但是之前我使用其他模型（不同的项目文件）在该数据集上进行单机多卡训练时，并未出现如上问题。
  2、不太可能是pytorch版本的问题。开始我考虑过可能是pytorch版本与NCCL版本可能不太适配，于是我按照我之前顺利使用单机多卡训练的项目的环境，来重新安装了较为一致的pytorch环境，并在版本更迭产生的可能会出错的代码进行了更改。
  3、单卡训练应该是没有问题的，只是对单卡的显存要求比较高了，需要在A100这样的显卡上单卡训练。
  4、关闭了opencv的多线程。因为训练代码中对dataset的处理，有用opencv相关操作，看网上说有可能是OpenCV与Pytorch互锁，于是在在import cv2后面添加cv2.setNumThreads(0)和cv2.ocl.setUseOpenCL(False)。
  5、降低num_workers值；通过torch.set_num_threads()调整pytorch的线程数。
  6、在loss.backward之前加了dist.barrier()
  7、启动训练脚本时，设置了OMP_NUM_THREADS=1和NCCL_P2P_DISABLE=1：
        
这个问题实在是很困扰我，我也排查了训练代码，也不知道究竟是哪里出现了问题。请问作者在使用多卡训练的时候，会出现同样的问题吗？麻烦您可以解答一下，十分感谢！

**Comment by Mang30** [comment]
@congyi-lcy 同学你好，你这个问题解决了吗？我在训练带有MOE的混合模型时也遇到了这个问题，搞了小一周了，我很头疼。
